import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{
          display: "flex",
          border: "1px solid red",
          justifyContent: "center",
          alignContent: "center",
          width: "600px",
          margin: "auto",
        }}
      >
        {children}
      </body>
    </html>
  );
}
