"use client";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import styled from "styled-components";
import {BrowserView, MobileView, isDesktop, isTablet, isMobileOnly} from "react-device-detect";
import Header from "./_component/Header";
const inter = Inter({subsets: ["latin"]});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        {isDesktop ? (
          <BrowserView>
            <DesktopLayout>
              <Header />
              {children}
            </DesktopLayout>
          </BrowserView>
        ) : isTablet ? (
          <MobileView>
            <TabletLayout>{children}</TabletLayout>
          </MobileView>
        ) : (
          <MobileView>
            <MobileLayout>{children}</MobileLayout>
          </MobileView>
        )}
      </body>
    </html>
  );
}

const DesktopLayout = styled.div`
  border: 1px solid blue;
  max-width: 1100px; //나머지 영역은 여백으로 남겨둠
  margin: auto; //자동 중앙정렬
`;
const TabletLayout = styled.div`
  border: 1px solid green;
  max-width: 600px; //나머지 영역은 여백으로 남겨둠?? -> 고민
  margin: auto; //자동 중앙정렬
`;
const MobileLayout = styled.div`
  border: 1px solid red;
  max-width: 600px;
  margin: auto;
`;
